// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go-peptide. DO NOT EDIT.
// source: cmd/protoc-gen-go-peptide/testdata/gogo/customtype.proto

package gogo

import (
	_ "github.com/monax/peptide/types/gogoproto"
	peptide "github.com/monax/peptide/types/peptide"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

type CustomTypeMessage struct {
	CustomTypeMessage
	Hash3 *Hash `peptide:"wraps=CustomTypeMessagePB" protobuf:"bytes,4,opt,name=Hash3,proto3" json:"Hash3,omitempty"`
}

type CustomTypeMessagePB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
	peptide.NoopExtender

	Hash  Hash   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Hash2 Hash   `protobuf:"bytes,3,opt,name=Hash2,proto3" json:"Hash2,omitempty"`
	Hash3 []byte `protobuf:"bytes,4,opt,name=Hash3,proto3" json:"Hash3,omitempty"`
}

func (x *CustomTypeMessagePB) Reset() {
	*x = CustomTypeMessagePB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (*CustomTypeMessagePB) ProtoMessage() {}

func (x *CustomTypeMessagePB) ProtoReflect() protoreflect.Message {
	return x.ProtoExtend(x.protoReflect())
}

func (x *CustomTypeMessagePB) protoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomTypeMessagePB.ProtoReflect.Descriptor instead.
func (*CustomTypeMessagePB) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescGZIP(), []int{0}
}

func (x *CustomTypeMessagePB) GetHash() Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CustomTypeMessagePB) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CustomTypeMessagePB) GetHash2() Hash {
	if x != nil {
		return x.Hash2
	}
	return nil
}

func (x *CustomTypeMessagePB) GetHash3() []byte {
	if x != nil {
		return x.Hash3
	}
	return nil
}

var File_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto protoreflect.FileDescriptor

var file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDesc = []byte{
	0x0a, 0x38, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x65, 0x70, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x65, 0x70, 0x74,
	0x69, 0x64, 0x65, 0x2e, 0x67, 0x6f, 0x67, 0x6f, 0x67, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xce, 0x01, 0x0a, 0x11, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5d, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x42, 0x49, 0xfa, 0xde, 0x1f, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6e, 0x61, 0x78, 0x2f, 0x70, 0x65, 0x70, 0x74, 0x69,
	0x64, 0x65, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x65, 0x70, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x05, 0x48,
	0x61, 0x73, 0x68, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x08, 0xfa, 0xde, 0x1f, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x05, 0x48, 0x61, 0x73, 0x68, 0x32, 0x12, 0x1e, 0x0a, 0x05, 0x48,
	0x61, 0x73, 0x68, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x08, 0xda, 0xde, 0x1f, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x05, 0x48, 0x61, 0x73, 0x68, 0x33, 0x3a, 0x04, 0x98, 0xa0, 0x1f,
	0x00, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x6f, 0x6e, 0x61, 0x78, 0x2f, 0x70, 0x65, 0x70, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x63, 0x6d,
	0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d,
	0x70, 0x65, 0x70, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescData = file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDesc
)

func file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescData)
	})
	return file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDescData
}

var file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_goTypes = []interface{}{
	(*CustomTypeMessagePB)(nil), // 0: peptide.gogogo.CustomTypeMessage
}
var file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_init() }
func file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_init() {
	if File_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomTypeMessagePB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_depIdxs,
		MessageInfos:      file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_msgTypes,
	}.Build()
	File_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto = out.File
	file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_rawDesc = nil
	file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_goTypes = nil
	file_cmd_protoc_gen_go_peptide_testdata_gogo_customtype_proto_depIdxs = nil
}
