// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go-peptide. DO NOT EDIT.
// source: cmd/protoc-gen-go-peptide/testdata/gogo/gogogo.proto

package gogo

import (
	_ "github.com/monax/peptide/types/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

type TestMessage_WithoutCompare int32

const (
	Apples  TestMessage_WithoutCompare = 0
	Oranges TestMessage_WithoutCompare = 1
)

// Enum value maps for TestMessage_WithoutCompare.
var (
	TestMessage_WithoutCompare_name = map[int32]string{
		0: "A",
		1: "O",
	}
	TestMessage_WithoutCompare_value = map[string]int32{
		"A": 0,
		"O": 1,
	}
)

func (x TestMessage_WithoutCompare) Enum() *TestMessage_WithoutCompare {
	p := new(TestMessage_WithoutCompare)
	*p = x
	return p
}

func (x TestMessage_WithoutCompare) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestMessage_WithoutCompare) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_enumTypes[0].Descriptor()
}

func (TestMessage_WithoutCompare) Type() protoreflect.EnumType {
	return &file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_enumTypes[0]
}

func (x TestMessage_WithoutCompare) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestMessage_WithoutCompare.Descriptor instead.
func (TestMessage_WithoutCompare) EnumDescriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescGZIP(), []int{0, 0}
}

type TestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithMoreTags string                     `protobuf:"bytes,1,opt,name=with_more_tags,json=withMoreTags,proto3" json:"with_more_tags,omitempty" we:"need_more_tags"`
	WithJsonTag  bool                       `protobuf:"varint,2,opt,name=with_json_tag,json=withJsonTag,proto3" json:"my_json_tag,omitempty"`
	Fruit        TestMessage_WithoutCompare `protobuf:"varint,3,opt,name=Fruit,proto3,enum=goproto.protoc.gogo.TestMessage_WithoutCompare" json:"Fruit,omitempty"`
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetWithMoreTags() string {
	if x != nil {
		return x.WithMoreTags
	}
	return ""
}

func (x *TestMessage) GetWithJsonTag() bool {
	if x != nil {
		return x.WithJsonTag
	}
	return false
}

func (x *TestMessage) GetFruit() TestMessage_WithoutCompare {
	if x != nil {
		return x.Fruit
	}
	return Apples
}

var File_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto protoreflect.FileDescriptor

var file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDesc = []byte{
	0x0a, 0x34, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x65, 0x70, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x67, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x67, 0x6f, 0x67, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x81, 0x02, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x5f, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0xf2, 0xde, 0x1f, 0x13, 0x77,
	0x65, 0x3a, 0x22, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x6d, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x61, 0x67,
	0x73, 0x22, 0x52, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x4d, 0x6f, 0x72, 0x65, 0x54, 0x61, 0x67, 0x73,
	0x12, 0x33, 0x0a, 0x0d, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x74, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x42, 0x0f, 0xea, 0xde, 0x1f, 0x0b, 0x6d, 0x79, 0x5f,
	0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x74, 0x61, 0x67, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x4a, 0x73,
	0x6f, 0x6e, 0x54, 0x61, 0x67, 0x12, 0x45, 0x0a, 0x05, 0x46, 0x72, 0x75, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x52, 0x05, 0x46, 0x72, 0x75, 0x69, 0x74, 0x22, 0x37, 0x0a, 0x0e,
	0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x11,
	0x0a, 0x01, 0x41, 0x10, 0x00, 0x1a, 0x0a, 0x8a, 0x9d, 0x20, 0x06, 0x41, 0x70, 0x70, 0x6c, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x01, 0x4f, 0x10, 0x01, 0x1a, 0x0b, 0x8a, 0x9d, 0x20, 0x07, 0x4f, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6e, 0x61, 0x78, 0x2f, 0x70, 0x65, 0x70, 0x74, 0x69, 0x64,
	0x65, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x65, 0x70, 0x74, 0x69, 0x64, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescData = file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDesc
)

func file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescData)
	})
	return file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDescData
}

var file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_goTypes = []interface{}{
	(TestMessage_WithoutCompare)(0), // 0: goproto.protoc.gogo.TestMessage.WithoutCompare
	(*TestMessage)(nil),             // 1: goproto.protoc.gogo.TestMessage
}
var file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_depIdxs = []int32{
	0, // 0: goproto.protoc.gogo.TestMessage.Fruit:type_name -> goproto.protoc.gogo.TestMessage.WithoutCompare
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_init() }
func file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_init() {
	if File_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_depIdxs,
		EnumInfos:         file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_enumTypes,
		MessageInfos:      file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_msgTypes,
	}.Build()
	File_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto = out.File
	file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_rawDesc = nil
	file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_goTypes = nil
	file_cmd_protoc_gen_go_peptide_testdata_gogo_gogogo_proto_depIdxs = nil
}
